name = "quill-blog-api"
main = "worker.ts"
compatibility_date = "2024-01-01"

# R2 bucket binding for blog assets
[[r2_buckets]]
binding = "BLOG_BUCKET"
bucket_name = "quill-auto-blogger"

# Environment variables
[vars]
CLOUDFLARE_API_TOKEN = ""

# Development settings
[dev]
port = 8787

# Production settings
[env.production]
name = "quill-blog-api-prod"

# R2 bucket binding for production
[[env.production.r2_buckets]]
binding = "BLOG_BUCKET"
bucket_name = "quill-auto-blogger"

# Staging environment
[env.staging]
name = "quill-blog-api-staging"

# R2 bucket binding for staging
[[env.staging.r2_buckets]]
binding = "BLOG_BUCKET"
bucket_name = "quill-auto-blogger"
