name = "blog-ai-worker"
main = "index.js"
compatibility_date = "2025-08-30"

[ai]
binding = "AI"

# KV store for prompts
[[kv_namespaces]]
binding = "PROMPTS_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# Environment variables for blog configuration
[vars]
BLOG_AUTHOR = "Paul Chris Luke"
BLOG_BASE_URL = "https://paulchrisluke.com"
BLOG_DEFAULT_IMAGE = "https://paulchrisluke.com/default.jpg"
# CORS allowed origins (comma-separated list, or '*' for development)
ALLOWED_ORIGINS = "*"

[env.production]
name = "blog-ai-worker"
# Production: restrict to specific origins
ALLOWED_ORIGINS = "https://paulchrisluke.com,https://www.paulchrisluke.com"

[env.staging]
name = "blog-ai-worker-staging"
# Staging: allow all origins for testing
ALLOWED_ORIGINS = "*"
